TRAIN:
  MAX_ITER: 100000
MODEL:
  NUM_CLASSES: 51
DATASETS:
  TRAIN:
    NAME: 'HMDB51'
    STEP_BETWEEN_CLIPS: 16
    FRAMES_PER_CLIP: 16
    VIDEO_DIR: 'data/hmdb51/hmdb51_org'
    ANNOTATION_DIR: 'data/hmdb51/testTrainMulti_7030_splits'
  TEST:
    NAME: 'HMDB51'
    STEP_BETWEEN_CLIPS: 16
    FRAMES_PER_CLIP: 16
    VIDEO_DIR: 'data/hmdb51/hmdb51_org'
    ANNOTATION_DIR: 'data/hmdb51/testTrainMulti_7030_splits'
OPTIMIZER:
  NAME: 'sgd'
  LR: 1e-3
  WEIGHT_DECAY: 3e-5
  MOMENTUM: 0.9
  GAMMA: 0.5
LR_SCHEDULER:
  NAME: 'multistep_lr'
  # for MultiStepLR
  MILESTONES: [ 25000, 60000 ]
OUTPUT:
  DIR: 'outputs/hmdb51'