TRAIN:
  MAX_ITER: 100000
MODEL:
  NUM_CLASSES: 101
DATASETS:
  TRAIN:
    NAME: 'UCF101'
    STEP_BETWEEN_CLIPS: 16
    FRAMES_PER_CLIP: 16
    VIDEO_DIR: 'data/ucf101/UCF-101'
    ANNOTATION_DIR: 'data/ucf101/ucfTrainTestlist'
  TEST:
    NAME: 'UCF101'
    STEP_BETWEEN_CLIPS: 16
    FRAMES_PER_CLIP: 16
    VIDEO_DIR: 'data/ucf101/UCF-101'
    ANNOTATION_DIR: 'data/ucf101/ucfTrainTestlist'
OPTIMIZER:
  NAME: 'sgd'
  LR: 1e-3
  WEIGHT_DECAY: 3e-5
  MOMENTUM: 0.9
  GAMMA: 0.5
LR_SCHEDULER:
  NAME: 'multistep_lr'
  # for SteLR
  STEP_SIZE: 400
  # for MultiStepLR
  MILESTONES: [ 25000, 60000 ]
OUTPUT:
  DIR: 'outputs/ucf101'